name: C/C++ CI - Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C https://github.com/Harshitha73/StepIn_MiniProject/tree/main/Implementation
    
